---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "è¯—å¾€å“¥å¯¼èˆª"
subtitle: "shiwange"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">â¤ï¸</span> with <a href="https://bulma.io/">Bulma</a>, <a href="https://vuejs.org/">Vue.js</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default

columns: "3"

defaults:
  layout: list

# Optional message
message:
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "ğŸ‘‹ æ¬¢è¿ !"
  content: "å½“å…¨ä¸–ç•ŒæŠ›å¼ƒä½ æ—¶ï¼Œä½ èº«ä¸Šæœ‰ä¸Šäº¿ä¸ªç»†èƒéƒ½ä¸ºä½ è€Œæ´»ã€‚"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute!"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Documentation"
    icon: "fas fa-book"
    url: "https://github.com/bastienwirtz/homer/blob/main/README.md#table-of-contents"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "åŸºç¡€æ•™è‚²"
    icon: "fa-solid fa-bookmark"
    class: ""
    items:
      - name: "ä¹‰åŠ¡æ•™è‚²è¯¾ç¨‹æ ‡å‡†"
        icon: "fa-solid fa-book"
        url: ""
        quick:
          - name: "äººæ°‘æ•™è‚²å‡ºç‰ˆç¤¾"
            url: "https://www.pep.com.cn/xw/zt/rjwy/gzkb2020/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
          - name: "æ•™è‚²éƒ¨"
            url: "https://www.gov.cn/zhengce/zhengceku/2022-04/21/content_5686535.htm"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
        
      - name: "æ™®é€šé«˜ä¸­è¯¾ç¨‹æ ‡å‡†"
        icon: "fa-solid fa-book"
        url: ""
        quick:
          - name: "äººæ°‘æ•™è‚²å‡ºç‰ˆç¤¾"
            url: "https://www.pep.com.cn/xw/zt/rjwy/yjkb2022/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
          - name: "æ•™è‚²éƒ¨"
            url: "http://www.moe.gov.cn/srcsite/A26/s8001/202006/t20200603_462199.html"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
      - name: "ç”µå­æ•™æ"
        icon: "fa-solid fa-book"
        url: ""
        quick:
          - name: "äººæ°‘æ•™è‚²å‡ºç‰ˆç¤¾"
            url: "https://jc.pep.com.cn/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
          - name: "æ™ºæ…§ä¸­å°å­¦ï¼ˆå¤šç‰ˆæœ¬ï¼‰"
            url: "https://basic.smartedu.cn/tchMaterial"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
      - name: "é¢˜åº“èµ„æº"
        icon: "fa-solid fa-file-word"
        url: ""
        quick:
          - name: "ç»„å·ç½‘ï¼ˆå­¦ç§‘ç½‘ï¼‰"
            url: "https://zujuan.xkw.com/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
          - name: "ä¹ç§‘æ˜Ÿï¼ˆé‡‘å¤ªé˜³ï¼‰"
            url: "https://www.jkxjxw.com/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"

  - name: "å­¦ç§‘å­¦ä¹ "
    icon: "fa-solid fa-video"
    class: "highlight-purple"
    items: 
      - name: "è¯­æ–‡"
        icon: "fa-brands fa-bilibili"
        subtitle: "å…è´¹ç³»ç»Ÿè¯¾"
        tag: "é«˜ä¸­"
        url: ""
        quick:
          - name: "å¥‡å“¥"
            url: "https://space.bilibili.com/39737405"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"

  - name: "é«˜ç­‰æ•™è‚²ä¸å‡å­¦"
    icon: "fa-solid fa-graduation-cap"
    class: "highlight-inverted"
    items:
      - name: "å¿—æ„¿å‚è€ƒ"
        icon: "fa-solid fa-link"
        tag: ""
        url: ""
        quick:
          - name: "é˜³å…‰å¿—æ„¿"
            url: "https://gaokao.chsi.com.cn/zyck/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
          - name: "æ¡†æ¡†å¤§å­¦"
            url: "https://www.kkdaxue.com/"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"
          - name: "å¤§å­¦ç”Ÿæ´»è´¨é‡æŒ‡åŒ—"
            url: "https://colleges.chat"
            icon: "fa-solid fa-arrow-up-right-from-square"
            target: "_blank"

